name: 'Deploy to Deta'
on: [push]
jobs:
  runs:
    runs-on: ubuntu-latest
    steps: 
      # Install Deta CLI as per docs
      # https://docs.deta.sh/docs/cli/install
      - name: Install Deta CLI
        shell: bash
        run: |
          curl -fsSL https://get.deta.dev/cli.sh | sh


      # Using the access token and existing Deta micro and project,
      # clone the micro and copy .deta metadata folder to use it in deploy
      # https://docs.deta.sh/docs/cli/commands#deta-clone
      - name: Clone Deta Metadata
        shell: bash
        run: |
          export DETA_ACCESS_TOKEN=${{ secrets.DETA_ACCESS_TOKEN }}
          ~/.deta/bin/deta clone --name api --project Makerfestival2021

      - name: Create env file
        shell: bash
        run: |
          touch ./api/env
          echo DETA_KEY=${{ secrets.DETA_KEY }} >> env

      # Using the access token, deploy the project to Deta
      # https://docs.deta.sh/docs/cli/commands#deta-deploy
      - name: Deploy to Deta 
        shell: bash
        run: |
          export DETA_ACCESS_TOKEN=${{ secrets.DETA_ACCESS_TOKEN }}
          cd api
          ~/.deta/bin/deta deploy